- name: Ensure freetds packages are installed
  apt: name={{item}} state=latest
  loop: "{{ freetds_packages|flatten(levels=1) }}"

- name: Set freetds config
  copy: src=freetds.conf dest={{freetds_confdir}}/ mode=0644